SOLVER:
  BATCH_SIZE: 64
  MAX_EPOCH: 200 #100
  LR: 5e-5  #5e-5
  SEED: 42 #42
  NUM_WORKERS: 128 #8

DA:
  TASK: False
  USE: False

DECODER:
  BINARY: 1

# Config below only when you use comet
COMET:
  PROJECT_NAME: "Drug_Random"
  TAG: "Non_DA"

